apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudapp-deployment
  labels:
    app: cloudapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudapp
  template:
    metadata:
      labels:
        app: cloudapp 
    spec:
      containers:
      - name: nodeserver
        image: bala3404/cloudapp:latest
        ports:
        - containerPort: 4000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: cloudapp-service
spec:
  selector:
    app: cloudapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 31717
